apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    url: http://jaeger-query:16686
    access: proxy
    editable: true
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
