services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    container_name: jaeger-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "14250:14250"
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=opensearch
      - ES_TAGS_AS_FIELDS_ALL=true
      - ES_TLS_SKIP_HOST_VERIFY=true
      - ES_SERVER_URLS=https://opensearch-node:9200
      - ES_TLS_ENABLED=true
      - ES_USERNAME=admin
      - ES_PASSWORD=K*ae_7EBekPt
      - ES_MAX_SPAN_AGE=720h0m0s
    networks:
      - observability-net

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger-query
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    restart: unless-stopped
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_TLS_ENABLED=false
      - SPAN_STORAGE_TYPE=opensearch
      - ES_TAGS_AS_FIELDS_ALL=true
      - ES_TLS_SKIP_HOST_VERIFY=true
      - ES_SERVER_URLS=https://opensearch-node:9200
      - ES_TLS_ENABLED=true
      - ES_USERNAME=admin
      - ES_PASSWORD=K*ae_7EBekPt
      - ES_MAX_SPAN_AGE=720h0m0s
    command:
      - "--query.ui-config=/etc/jaeger/config.json"
    volumes:
      - ./jaeger-query:/etc/jaeger
    networks:
      - observability-net

  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=K*ae_7EBekPt
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - observability-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]'
      opensearch.username: admin
      opensearch.password: K*ae_7EBekPt
    networks:
      - observability-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - observability-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - observability-net

volumes:
  prom_data:
  opensearch-data:

networks:
  observability-net:
