services:
  db:
    image: docker.io/postgres:12
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: adminpwd!

volumes:
  pg-volume:
